# Generated by Django 4.2.4 on 2023-09-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ammarentaladmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='totalprice',
        ),
    ]
