# Generated by Django 4.2.5 on 2023-09-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
