# Generated by Django 4.2.5 on 2023-09-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_travelinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelInfo',
        ),
    ]
